
export const RandomWordAndHint = () => {
    const words = [
        { word: 'apple', hint: 'A fruit' },
        { word: 'orange', hint: 'A fruit' },
        { word: "banana", hint: "A yellow fruit" },
        { word: "computer", hint: "An electronic device" },
        { word: "ocean", hint: "A large body of water" },
        { word: "guitar", hint: "A musical instrument" },
        { word: "book", hint: "Contains written information" },
        { word: "dog", hint: "A common pet" },
        { word: "mountain", hint: "A tall natural landform" },
        { word: "basketball", hint: "A sports ball used in a game" },
        { word: "pizza", hint: "A popular Italian dish" },
        { word: "bicycle", hint: "A two-wheeled vehicle" },
        { word: "sunglasses", hint: "Protects your eyes from the sun" },
        { word: "garden", hint: "A place to grow plants" },
        { word: "television", hint: "A device for watching shows" },
        { word: "keyboard", hint: "Used for typing on a computer" },
        { word: "camera", hint: "Used to capture photos" },
        { word: "tree", hint: "A tall plant with branches" },
        { word: "shoes", hint: "Footwear for your feet" },
        { word: "music", hint: "Melodies and rhythms" },
        { word: "beach", hint: "Sandy shore by the sea" },
        { word: "umbrella", hint: "Keeps you dry in the rain" },
        { word: "movie", hint: "A film for entertainment" },
        { word: "moon", hint: "Earth's natural satellite" },
        { word: "jacket", hint: "Keeps you warm in cold weather" },
        { word: "pencil", hint: "Used for writing and drawing" },
        { word: "clock", hint: "Tells you the time" },
        { word: "flower", hint: "Blooms in gardens" },
        { word: "phone", hint: "Communication device" },
        { word: "cake", hint: "Sweet dessert" },
        { word: "door", hint: "Entrance to a room" },
        { word: "cloud", hint: "Visible mass of water vapor" },
        { word: "chair", hint: "For sitting" },
        { word: "map", hint: "Shows locations" },
        { word: "wallet", hint: "Holds money and cards" },
        { word: "hat", hint: "Worn on the head" },
        { word: "globe", hint: "Represents the Earth" },
        { word: "mirror", hint: "Reflects your image" },
        { word: "cookie", hint: "Sweet treat" },
        { word: "carrot", hint: "Orange vegetable" },
        { word: "swimming", hint: "Activity in the water" },
        { word: "fire", hint: "Produces heat and light" },
        { word: "camera", hint: "Captures memories" },
        { word: "socks", hint: "Worn on your feet" },
        { word: "key", hint: "Unlocks doors" },
        { word: "globe", hint: "Represents the world" },
        { word: "painting", hint: "Art on canvas" },
        { word: "moon", hint: "Lunar body" },
        { word: "chocolate", hint: "Sweet indulgence" },
        { word: "phone", hint: "Communication device" },
        { word: "computer", hint: "Electronic tool" }
    ];
    const randomIndex = Math.floor(Math.random() * words.length);
    return words[randomIndex];
};
