
export const RandomWordAndHint = () => {
    const words = [
        { word: 'orange', hint: 'A fruit' },
        { word: "banana", hint: "A yellow fruit" },
        { word: "computer", hint: "An electronic device" },
        { word: "ocean", hint: "A large body of water" },
        { word: "guitar", hint: "A musical instrument" },
        { word: "book", hint: "Contains written information" },
        { word: "mountain", hint: "A tall natural landform" },
        { word: "basketball", hint: "A sports ball used in a game" },
        { word: "pizza", hint: "A popular Italian dish" },
        { word: "bicycle", hint: "A two-wheeled vehicle" },
        { word: "sunglasses", hint: "Protects your eyes from the sun" },
        { word: "garden", hint: "A place to grow plants" },
        { word: "television", hint: "A device for watching shows" },
        { word: "jacket", hint: "Keeps you warm in cold weather" },
        { word: "pencil", hint: "Used for writing and drawing" },
        { word: "clock", hint: "Tells you the time" },
        { word: "cloud", hint: "Visible mass of water vapor" },
        { word: "chair", hint: "For sitting" },
        { word: "wallet", hint: "Holds money and cards" },
        { word: "hat", hint: "Worn on the head" },
        { word: "globe", hint: "Represents the Earth" },
        { word: "mirror", hint: "Reflects your image" },
        { word: "cookie", hint: "Sweet treat" },
        { word: "carrot", hint: "Orange vegetable" },
        { word: "swimming", hint: "Activity in the water" },
        { word: "fire", hint: "Produces heat and light" },
        { word: "camera", hint: "Captures memories" },
        { word: "socks", hint: "Worn on your feet" },
        { word: "key", hint: "Unlocks doors" },
        { word: "globe", hint: "Represents the world" },
        { word: "painting", hint: "Art on canvas" },
        { word: "moon", hint: "Lunar body" },
        { word: "chocolate", hint: "Sweet indulgence" },
        { word: "sycophant", hint: "A person who acts obsequiously towards someone important in order to gain an advantage." },
        { word: "obfuscate", hint: "To render obscure, unclear, or unintelligible." },
        { word: "pernicious", hint: "Having a harmful effect, especially in a gradual or subtle way." },
        { word: "recumbentibus", hint: "A provoking criticism, or a well-founded complaint." },
        { word: "sagacious", hint: "Having or showing keen mental discernment and good judgment; shrewd." },
        { word: "taciturn", hint: "Reserved or uncommunicative in speech; saying little." },
        { word: "umbra", hint: "The fully shaded inner region of a shadow cast by an opaque object." },
        { word: "vexatious", hint: "Causing annoyance, frustration, or worry." },
        { word: "wraith", hint: "A ghost or ghostlike image of someone, especially one seen shortly before or after their death." },
        { word: "xenophobe", hint: "A person who dislikes or is prejudiced against people from other countries." },
        { word: "yoke", hint: "A wooden crosspiece that is fastened over the necks of two animals and attached to the plow or cart that they are to pull." },
        { word: "zephyr", hint: "A gentle, mild breeze." },
        { word: "verisimilitude", hint: "The appearance of being true or real." },
        { word: "oxymoron", hint: "A figure of speech in which apparently contradictory terms appear in conjunction." },
        { word: "kleidoscope", hint: "A constantly changing pattern or sequence of elements." },
        { word: "reticent", hint: "Not revealing one's thoughts or feelings readily." },
        { word: "munificent", hint: "More generous than is usual or necessary." },
        { word: "nocturnal", hint: "Done, occurring, or active at night." },
        { word: "Acumen", hint: "The ability to make good judgments and quick decisions." },
        { word: "benevolent", hint: "Well-meaning and kindly." },
        { word: "cacophony", hint: "A harsh, discordant mixture of sounds." },
        { word: "debilitate", hint: "Make (someone) weak and infirm." },
        { word: "eloquent", hint: "Fluent or persuasive in speaking or writing." },
        { word: "facetious", hint: "Treating serious issues with deliberately inappropriate humor." },
        { word: "garrulous", hint: "Excessively talkative, especially on trivial matters." },
        { word: "hapless", hint: "Unfortunate." },
        { word: "ineffable", hint: "Too great or extreme to be expressed or described in words." },
        { word: "juxtapose", hint: "To place or deal with close together for contrasting effect." },
        { word: "kaleidoscope", hint: "A constantly changing pattern or sequence of elements." },
        { word: "languish", hint: "Lose or lack vitality; grow weak or feeble." },
        { word: "meticulous", hint: "Showing great attention to detail; very careful and precise." },
        { word: "nefarious", hint: "Wicked, villainous, or heinously infamous." },
        { word: "obfuscate", hint: "To render obscure, unclear, or unintelligible." },
        { word: "pernicious", hint: "Having a harmful effect, especially in a gradual or subtle way." },
        { word: "quixotic", hint: "Exceedingly idealistic; unrealistic and impractical." },
        { word: "rambunctious", hint: "Uncontrollably exuberant; boisterous." },
        { word: "sycophant", hint: "A person who acts obsequiously towards someone important in order to gain an advantage." },
        { word: "taciturn", hint: "Reserved or uncommunicative in speech; saying little." },
        { word: "ubiquitous", hint: "Present, appearing, or found everywhere." },
        { word: "voracious", hint: "Wanting or devouring great quantities of food; having a very eager approach to an activity." },
        { word: "whimsical", hint: "Playfully quaint or fanciful, especially in an appealing and amusing way." },
        { word: "xenophile", hint: "A person who is attracted to foreign peoples, cultures, or customs." },
        { word: "yearn", hint: "Have an intense feeling of longing for something." },
        { word: "zealous", hint: "Showing great energy or enthusiasm in pursuit of a cause or objective." },
        { word: "amicable", hint: "Having a spirit of friendliness; without serious disagreement or rancor." },
        { word: "belligerent", hint: "Hostile and aggressive." },
        { word: "circumspect", hint: "Wary and unwilling to take risks." },
        { word: "deleterious", hint: "Causing harm or damage." },
        { word: "ephemeral", hint: "Lasting for a very short time; fleeting." },
        { word: "furtive", hint: "Attempting to avoid notice or attention, typically because of guilt or a belief that discovery would lead to trouble." },
        { word: "gregarious", hint: "Fond of company; sociable." },
        { word: "hapless", hint: "Unfortunate." },
        { word: "ineffable", hint: "Too great or extreme to be expressed or described in words." },
        { word: "juxtapose", hint: "To place or deal with close together for contrasting effect." },
        { word: "kaleidoscope", hint: "A constantly changing pattern or sequence of elements." },
        { word: "languish", hint: "Lose or lack vitality; grow weak or feeble." },
        { word: "meticulous", hint: "Showing great attention to detail; very careful and precise." },
        { word: "nefarious", hint: "Wicked, villainous, or heinously infamous." },
        { word: "obfuscate", hint: "To render obscure, unclear, or unintelligible." },
        { word: "pernicious", hint: "Having a harmful effect, especially in a gradual or subtle way." },
        { word: "quixotic", hint: "Exceedingly idealistic; unrealistic and impractical." },
        { word: "rambunctious", hint: "Uncontrollably exuberant; boisterous." },
        { word: "sycophant", hint: "A person who acts obsequiously towards someone important in order to gain an advantage." },
        { word: "taciturn", hint: "Reserved or uncommunicative in speech; saying little." },
        { word: "ubiquitous", hint: "Present, appearing, or found everywhere." },
        { word: "voracious", hint: "Wanting or devouring great quantities of food; having a very eager approach to an activity." },
        { word: "whimsical", hint: "Playfully quaint or fanciful, especially in an appealing and amusing way." },
        { word: "xenophile", hint: "A person who is attracted to foreign peoples, cultures, or customs." },
        { word: "yearn", hint: "Have an intense feeling of longing for something." },
        { word: "zealous", hint: "Showing great energy or enthusiasm in pursuit of a cause or objective." }
    ];
    const randomIndex = Math.floor(Math.random() * words.length);
    return words[randomIndex];
};
