
export const RandomWordAndHint = () => {
    const words = [
        { word: 'orange', hint: 'A fruit' },
        { word: "banana", hint: "A yellow fruit" },
        { word: "computer", hint: "An electronic device" },
        { word: "ocean", hint: "A large body of water" },
        { word: "guitar", hint: "A musical instrument" },
        { word: "book", hint: "Contains written information" },
        { word: "mountain", hint: "A tall natural landform" },
        { word: "basketball", hint: "A sports ball used in a game" },
        { word: "pizza", hint: "A popular Italian dish" },
        { word: "bicycle", hint: "A two-wheeled vehicle" },
        { word: "sunglasses", hint: "Protects your eyes from the sun" },
        { word: "garden", hint: "A place to grow plants" },
        { word: "television", hint: "A device for watching shows" },
        { word: "jacket", hint: "Keeps you warm in cold weather" },
        { word: "pencil", hint: "Used for writing and drawing" },
        { word: "clock", hint: "Tells you the time" },
        { word: "cloud", hint: "Visible mass of water vapor" },
        { word: "chair", hint: "For sitting" },
        { word: "wallet", hint: "Holds money and cards" },
        { word: "hat", hint: "Worn on the head" },
        { word: "globe", hint: "Represents the Earth" },
        { word: "mirror", hint: "Reflects your image" },
        { word: "cookie", hint: "Sweet treat" },
        { word: "carrot", hint: "Orange vegetable" },
        { word: "swimming", hint: "Activity in the water" },
        { word: "fire", hint: "Produces heat and light" },
        { word: "camera", hint: "Captures memories" },
        { word: "socks", hint: "Worn on your feet" },
        { word: "key", hint: "Unlocks doors" },
        { word: "globe", hint: "Represents the world" },
        { word: "painting", hint: "Art on canvas" },
        { word: "moon", hint: "Lunar body" },
        { word: "chocolate", hint: "Sweet indulgence" },
        { word: "Sycophant", hint: "A person who acts obsequiously towards someone important in order to gain an advantage."},
        { word: "Obfuscate", hint: "To render obscure, unclear, or unintelligible."},
        { word: "Pernicious", hint: "Having a harmful effect, especially in a gradual or subtle way."},
        { word: "Ineffable", hint: "Too great or extreme to be expressed or described in words."},
        { word: "Inchoate", hint: "Just begun and so not fully formed or developed; rudimentary."},
        { word: "Lugubrious", hint: "Looking or sounding sad and dismal."},
        { word: "Quixotic", hint: "Exceedingly idealistic; unrealistic and impractical."},
        { word: "Mellifluous", hint: "Sweetly flowing or sounding."},
        { word: "Nefarious", hint: "Wicked, villainous, or heinously infamous."},
        { word: "Mendacious", hint: "Not telling the truth; lying."},
        { word: "Esoteric", hint: "Intended for or likely to be understood by only a small number of people with a specialized knowledge or interest."},
        { word: "Cacophony", hint: "A harsh, discordant mixture of sounds."},
        { word: "Voracious", hint: "Wanting or devouring great quantities of food; having a very eager approach to an activity."},
        { word: "Surreptitious", hint: "Kept secret, especially because it would not be approved of."},
        { word: "Supercilious", hint: "Behaving or looking as though one thinks one is superior to others."},
        { word: "Querulous", hint: "Complaining in a petulant or whining manner."},
        { word: "Recalcitrant", hint: "Having an obstinately uncooperative attitude toward authority or discipline."},
        { word: "Parsimonious", hint: "Unwilling to spend money or use resources; stingy or frugal."},
        { word: "Idiosyncratic", hint: "Peculiar or individual."},
        { word: "Lethargic", hint: "Affected by lethargy; sluggish and apathetic."},
        { word: "Obstreperous", hint: "Noisy and difficult to control."},
        { word: "Perfidious", hint: "Deceitful and untrustworthy."},
        { word: "Quotidian", hint: "Of or occurring every day; daily."},
        { word: "Recumbentibus", hint: "A provoking criticism, or a well-founded complaint."},
        { word: "Sagacious", hint: "Having or showing keen mental discernment and good judgment; shrewd."},
        { word: "Taciturn", hint: "Reserved or uncommunicative in speech; saying little."},
        { word: "Umbra", hint: "The fully shaded inner region of a shadow cast by an opaque object."},
        { word: "Vexatious", hint: "Causing annoyance, frustration, or worry."},
        { word: "Wraith", hint: "A ghost or ghostlike image of someone, especially one seen shortly before or after their death."},
        { word: "Xenophobe", hint: "A person who dislikes or is prejudiced against people from other countries."},
        { word: "Yoke", hint: "A wooden crosspiece that is fastened over the necks of two animals and attached to the plow or cart that they are to pull."},
        { word: "Zephyr", hint: "A gentle, mild breeze."},
        { word: "Verisimilitude", hint: "The appearance of being true or real."},
        { word: "Oxymoron", hint: "A figure of speech in which apparently contradictory terms appear in conjunction."},
        { word: "Kaleidoscope", hint: "A constantly changing pattern or sequence of elements."},
        { word: "Reticent", hint: "Not revealing one's thoughts or feelings readily."},
        { word: "Munificent", hint: "More generous than is usual or necessary."},
        { word: "Nocturnal", hint: "Done, occurring, or active at night."},
        { word: "Oblivion", hint: "The state of being unaware or unconscious of what is happening."},
        { word: "Panacea", hint: "A solution or remedy for all difficulties or diseases."},
        { word: "Quintessential", hint: "Representing the most perfect or typical example of a quality or class."},
        { word: "Rambunctious", hint: "Uncontrollably exuberant; boisterous."},
        { word: "Serendipity", hint: "A pleasant surprise or fortunate discovery by chance."},
        { word: "Truculent", hint: "Eager or quick to argue or fight; aggressively defiant."},
        { word: "Umbrage", hint: "Offense or annoyance."},
        { word: "Vorfreude", hint: "The joyful, intense anticipation that comes from imagining future pleasures."},
        { word: "Wanderlust", hint: "A strong desire to travel and explore the world."},
        { word: "Xerophyte", hint: "A plant that is adapted to live in a dry habitat."},
        { word: "Yuletide", hint: "The Christmas season."},
        { word: "Zoetic", hint: "Of or relating to life."},
        { word: "Ephemeral", hint: "Lasting for a very short time; fleeting."},
        { word: "Ubiquitous", hint: "Present, appearing, or found everywhere."}
        
    ];
    const randomIndex = Math.floor(Math.random() * words.length);
    return words[randomIndex];
};
